
# # 配置语言及相应版本
# language: node_js
# node_js: 12

# cache:
#   directories:
#     - node_modules

# # 配置环境
# before_install:
#   # 刚才生成的解密信息
#   - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
#   -in id_rsa.enc -out id_rsa -d
#   # 改变文件权限
#   - chmod 600 ~/.ssh/github_rsa 
#   # 配置ssh
#   - eval $(ssh-agent)
#   - ssh-add ~/.ssh/github_rsa
#   - cp .travis/ssh_config ~/.ssh/config
  
#   - git config --global user.name 'lm'
#   - git config --global user.email 'lmzs124083@163.com'
  
# install:
# - npm install hexo-cli -g
# # - npm install hexo -g
# - npm install

# # 部署的命令
# script:
# - npm run deploy  

# branches:
#   only:
#     - blog  

language: node_js #设置语言

node_js: "10.16.3" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo g
  - hexo algolia
  - hexo deploy
  

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - master